name: Protocol Land Sync
on:
    push:
        branches:
            - 'main'
    #workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout repo (default branch)'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 1
            - name: 'Setup node 18'
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - name: 'Clean and prepare'
              run: |
                find . -type d -name "node_modules" -exec rm -rf {} +
                find . -type d -name ".next" -exec rm -rf {} +
                find . -type d -name "dist" -exec rm -rf {} +
                find . -type d -name ".cache" -exec rm -rf {} +
                find . -type f -name "package-lock.json" -delete
            - name: 'Install dependencies and sync'
              run: |
                npm install -g @protocol.land/sync
                export NODE_OPTIONS="--max-old-space-size=4096"
                npx @protocol.land/sync --ignore-errors
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  REPO_TITLE: ${{ github.event.repository.name }}
                  REPO_DESCRIPTION: ${{ github.event.repository.description }}
                  WALLET: ${{ secrets.WALLET }}
                  NODE_ENV: production