name: Protocol Land Sync
on:
    push:
        branches:
            - 'main'
    #workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout repo (default branch)'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: 'Setup node 18'
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - name: 'Set proper permissions'
              run: |
                chmod -R 755 .
                git config --global --add safe.directory "$GITHUB_WORKSPACE"
            - name: 'Clean and prepare'
              run: |
                find . -name "node_modules" -type d -prune -exec rm -rf '{}' +
                find . -name ".git" -type d -prune -exec rm -rf '{}' +
            - name: 'Sync repo to Protocol Land'
              run: npm i -g @protocol.land/sync && npx @protocol.land/sync
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  REPO_TITLE: ${{ github.event.repository.name }}
                  REPO_DESCRIPTION: ${{ github.event.repository.description }}
                  WALLET: ${{ secrets.WALLET }}