name: Protocol Land Sync
on:
    push:
        branches:
            - 'main'
    #workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout repo (default branch)'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 1
            - name: 'Setup node 18'
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - name: 'Set full permissions'
              run: |
                sudo chmod -R 777 .
                sudo chown -R $USER:$USER .
                sudo git config --global --add safe.directory "$GITHUB_WORKSPACE"
            - name: 'Install and sync with elevated permissions'
              run: |
                sudo npm install -g @protocol.land/sync
                export NODE_OPTIONS="--max-old-space-size=4096"
                sudo npx @protocol.land/sync
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  REPO_TITLE: ${{ github.event.repository.name }}
                  REPO_DESCRIPTION: ${{ github.event.repository.description }}
                  WALLET: ${{ secrets.WALLET }}
                  NODE_ENV: production